version: "3"
services:
  users:
    build: ./user
    #restart: always
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "5432:5432"
    #env_file:
      #- ./web_dockerfile/.env
