version: "3"

services:
  gateway_nginx:
    image: nginx:stable
    container_name: gateway_nginx
    ports:
      - 80:80
    volumes:
      - ./static:/var/www/
      - ./nginx/:/etc/nginx/conf.d/
  gateway_php:
    image: php:fpm
    container_name: gateway_php