version: "3"

services:
  users_db:
    image: postgres:13.2
    container_name: users_postgres
    volumes:
      - ./postgresql/:/docker-entrypoint-initdb.d/
    env_file:
      - ./environment/prod.env
    networks:
      - users_backend
    depends_on:
      - users_nginx
  users_php:
    image: php:fpm
    container_name: users_php
    networks:
      - users_frontend
      - users_backend
  users_nginx:
    image: nginx:stable
    container_name: users_nginx
    ports:
      - 8088:80
    volumes:
      - ./static:/var/www/
      - ./nginx/:/etc/nginx/conf.d/
    networks:
      - users_frontend
    depends_on:
      - users_php

networks:
  users_frontend:
  users_backend:
