version: "3"

services:
  posts_db:
    image: postgres:13.2
    container_name: posts_postgres
    volumes:
      - ./postgresql/:/docker-entrypoint-initdb.d/
    env_file:
      - ./environment/prod.env
    networks:
      - posts_backend
    depends_on:
      - posts_nginx
  posts_php:
    image: php:fpm
    container_name: post_php
    networks:
      - post_backend
      - post_frontend
  posts_nginx:
    image: nginx:stable
    container_name: posts_nginx
    ports:
      - 8085:80
    volumes:
      - ./static:/var/www/
      - ./nginx/:/etc/nginx/conf.d/
    networks:
      - posts_frontend
    depends_on:
      - posts_php

networks:
  posts_frontend:
  posts_backend:

