version: "3"

services:
  posts_db:
    image: postgres:13.2
    container_name: posts_postgres
    volumes:
      - ./postgresql/:/docker-entrypoint-initdb.d/
    #environment:
      #- PGDATA: /var/lib/postgresql/data/
      #- POSTGRES_USER=www-data
      #- POSTGRES_PASSWORD=www-data
    env_file:
      - ./environment/prod.env
    networks:
      - posts_backend
    depends_on:
      - posts_nginx
    ports:
      - 5432:5432
  posts_php:
    build: ./php
    container_name: post_php
    networks:
      - posts_backend
      - posts_frontend
    volumes:
      - ./static/:/var/www/
  posts_nginx:
    image: nginx:stable
    container_name: posts_nginx
    ports:
      - 8085:80
    volumes:
      - ./static:/var/www/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - posts_frontend
    depends_on:
      - posts_php

networks:
  posts_frontend:
  posts_backend:
